[run]
dimension=2
tEnd=2.0
nStepmax=100000

# number of materials
nmat=2

# noutput equals -1 means we dump data at every time steps
nOutput=10

[amr]
level_min=2
level_max=4

use_block_data=yes
bx=8
by=8

# amr refine criterion use at init condition
# possible value: ALWAYS_REFINE, GEOMETRIC, SAME_AS_REGULAR_DYNAMICS
refine_criterion_at_init=GEOMETRIC
#refine_criterion_at_init=SAME_AS_REGULAR_DYNAMICS

# init step may contain calls to globalRefine
# if the following option is true, we interleave
# calls to load balancing in between globalRefine
# if the following option is false, a single load
# balancing operation is done at the end of
# globalRefine steps
enable_load_balance_during_init=false

# refine criterion (used during regular dynamics)
# example parameter for using LOHNER_UNSPLIT criterion
refine_criterion=LOHNER_UNSPLIT
epsilon_refine=0.1
epsilon_coarsen=0.0125
epsilon_lohner=0.02

# example parameter for using LOHNER_UNSPLIT criterion
#refine_criterion=SIMPLE_GRADIENT
#epsilon_refine=0.1
#epsilon_coarsen=0.01

# p4est connectivity type
connectivity=brick

# control MPI load balancing (number of time steps between two
# consecutive load balancing)
load_balancing_frequency=20

# control AMR cycle frequency (number of time steps between two
# consecutive AMR cycles)
cycle_frequency=10

#
# when using two AMR refinement criterion (one for init conditions,
# one of the rest of the simulation run), we may want to disable the first amr cycle
# to smooth the transition between the two AMR criterion.
#
disable_first_amr_cycle=yes

variable_used_to_compute_refine_criterion=rho_mix

time_integrator=RK2_SSP

[p4est_connectivity]
nbrick_x=1
nbrick_y=1

periodic_x=1
periodic_y=1

[mesh]
xmin=-1.0
ymin=-1.0

scaling_factor=2.0

boundary_type_xmin=ZERO_GRADIENT
boundary_type_xmax=ZERO_GRADIENT

boundary_type_ymin=ZERO_GRADIENT
boundary_type_ymax=ZERO_GRADIENT

[hydro]
cfl=0.5
slope_type=2
problem=droplet_advection
riemann=HLLC

[material0]
# water
name=water
mg_eos_name=MG_STIFFENED_GAS

[material0_mie_gruneisen_sg]
gamma=4.4
pinf=6000

[material1]
# air
name=air
mg_eos_name=MG_STIFFENED_GAS

[material1_mie_gruneisen_sg]
gamma=1.4
pinf=0

[region0]
alpha0=1.0
alpha_rho=1000.0,0.0
p=1.0
u=1.0
v=0.0

[region1]
alpha0=0.0
alpha_rho=0.0,1.0
p=1.0
u=1.0
v=0.0

[smooth_interface_function]
enabled=no
surface_tension_enabled=no
curvature_filter_iterations=10
output_variables=vol_frac,sif,normal_vector

[THINC]
enabled=no
beta=1.5
epsilon=1e-3

[droplet_advection]
radius=0.5
ux=1.0
uy=0.0
h=0.005

[output]
outputDir=./
outputPrefix=test_droplet_advection_2d_no_thinc
outputVtkAscii=false
write_variables=rho_mix,alpha_rho_0,alpha_rho_1,alpha_0,rho_vx,rho_vy,e_tot,rho_mix_schlieren,thermal_pressure
write_mesh_info=no
write_iOct=no
hdf5_enabled=yes
enable_writing_leaf_data=no
write_conformal_status=no
schlieren_scaling=SQRT
