#
# This test case soves a Riemann problem with TNT on both sides
#
# reference: see example 4 in reference
# High-order finite volume method for solving compressible multicomponent flows with
# Mie–Grüneisen equation of state. F. Zheng and J. Qiu, Computers & Fluids, Volume 284, 2024,
# 106424, ISSN 0045-7930.
# https://doi.org/10.1016/j.compfluid.2024.106424

[run]
dimension=2
tEnd=0.000012
nStepmax=5000

# number of materials
nmat=2

# noutput equals -1 means we dump data at every time steps
nOutput=10

[amr]
level_min=1
level_max=5

use_block_data=yes
bx=8
by=8

# amr refine criterion use at init condition
# possible value: ALWAYS_REFINE, GEOMETRIC, SAME_AS_REGULAR_DYNAMICS
refine_criterion_at_init=GEOMETRIC

# init step may contain calls to globalRefine
# if the following option is true, we interleave
# calls to load balancing in between globalRefine
# if the following option is false, a single load
# balancing operation is done at the end of
# globalRefine steps
enable_load_balance_during_init=false

# refine criterion (used during regular dynamics)
# example parameter for using LOHNER_UNSPLIT criterion
refine_criterion=LOHNER_UNSPLIT
epsilon_refine=0.4
epsilon_coarsen=0.05
epsilon_lohner=0.02

# example parameter for using LOHNER_UNSPLIT criterion
#refine_criterion=SIMPLE_GRADIENT
#epsilon_refine=0.1
#epsilon_coarsen=0.01

# p4est connectivity type
connectivity=brick

# control MPI load balancing (number of time steps between two
# consecutive load balancing)
load_balancing_frequency=20

# control AMR cycle frequency (number of time steps between two
# consecutive AMR cycles)
cycle_frequency=5

#
# when using two AMR refinement criterion (one for init conditions,
# one of the rest of the simulation run), we may want to disable the first amr cycle
# to smooth the transition between the two AMR criterion.
#
disable_first_amr_cycle=yes

#time_integrator=RK2_SSP

variable_used_to_compute_refine_criterion=alpha_rho_0,thermal_pressure

[p4est_connectivity]
nbrick_x=5
nbrick_y=1

periodic_x=0
periodic_y=0

[mesh]
xmin=0.0
ymin=0.0

scaling_factor=0.2

boundary_type_xmin=ZERO_GRADIENT
boundary_type_xmax=ZERO_GRADIENT

boundary_type_ymin=ZERO_GRADIENT
boundary_type_ymax=ZERO_GRADIENT

[smooth_interface_function]
enabled=no
surface_tension_enabled=no
curvature_filter_iterations=10
output_variables=vol_frac,sif,normal_vector

[THINC]
enabled=yes
beta=1.5
epsilon=1e-3

[hydro]
cfl=0.2
slope_type=1
problem=two_fluid_shock_tube
riemann=HLLC

[material0]
name=tnt
mg_eos_name=MG_JWL

[material0_mie_gruneisen_jwl]
# note: A1 and A2 are given in Pascal
rho0=1840
Gamma0=0.25
A1=854.5e9
A2=20.5e9
R1=4.6
R2=1.35
e0=0.0

[material1]
mg_eos_name=MG_JWL

[material1_mie_gruneisen_jwl]
# note: A1 and A2 are given in Pascal
rho0=1840
Gamma0=0.25
A1=854.5e9
A2=20.5e9
R1=4.6
R2=1.35
e0=0.0

[region0]
alpha0=1.0
alpha_rho=1700.0,0.0
p=1e12
u=0.0

[region1]
alpha0=0.0
alpha_rho=0.0,1000.0
p=5e10
u=0.0

[two_fluid_shock_tube]
# discontinuity location default to center box, i.e. (x_min + x_max) / 2
# but you can change it by setting xd
xd=0.5

[output]
outputDir=./
outputPrefix=test_two_fluid_shock_tube_2d_tnt
outputVtkAscii=false
write_variables=rho_mix,alpha_rho_0,alpha_rho_1,alpha_0,rho_vx,rho_vy,e_tot,thermal_pressure
write_mesh_info=yes
write_iOct=no
hdf5_enabled=yes
enable_writing_leaf_data=no
write_conformal_status=no
